### ISSUE TITLE
Addition of Google Maps

### ISSUE THREAD

**Issue by adityabisoi** [Awesome-React-Modules/React-Pincode-Website#21]
**Is your feature request related to a problem? Please describe.**
Google Maps can be added to the existing project for displaying the location of the query.

**Describe the solution you'd like**
A button would pop up on a valid Pincode input, which would redirect to a new webpage (Google Maps) showing the city generated from the query.

**Additional context**
Currently, no Google Maps API will be required.

@plxity  @yellowwoods12 I can work on this. Please assign it to me. Thanks.

**Comment by plxity** [comment]
@adityabisoi Done :+1:
